# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Product_name', models.CharField(max_length=100)),
                ('Store', models.CharField(max_length=100)),
            ],
        ),
    ]
