# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('Memory', models.CharField(max_length=200)),
                ('RAM', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.URLField()),
                ('store_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product_details',
            options={'verbose_name': 'Product Detail', 'verbose_name_plural': 'Product Details'},
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='Store',
        ),
        migrations.AddField(
            model_name='product_details',
            name='ProductID',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_details',
            name='Brand_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_details',
            name='Product_Category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_details',
            name='Product_Spec',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.Specification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_details',
            name='Store_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.Store'),
            preserve_default=False,
        ),
    ]
