# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0002_auto_20171209_1918'),
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=20)),
                ('listing_url', models.URLField(blank=True)),
                ('affiliate_url', models.URLField(blank=True)),
                ('current_price', models.CharField(blank=True, editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('capacity', models.CharField(blank=True, max_length=50)),
                ('images', models.TextField(blank=True)),
                ('best_current_price', models.CharField(blank=True, editable=False, max_length=20)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.URLField()),
                ('store_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Product_details',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.ProductVariant'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Store'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set([('product_model', 'color', 'capacity')]),
        ),
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together=set([('brand', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='productlisting',
            unique_together=set([('product_variant', 'store')]),
        ),
    ]
