# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_product_details_productid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_details',
            options={'verbose_name': 'Product Detail', 'verbose_name_plural': 'Product Details'},
        ),
    ]
