# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0002_auto_20171126_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name': 'Price History', 'verbose_name_plural': 'Price History'},
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Done At'),
        ),
    ]
