# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20171209_1918'),
        ('data_store', '0002_auto_20171209_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='listing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.ProductListing'),
            preserve_default=False,
        ),
    ]
