# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0003_auto_20171126_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
